testapp/testapp/apps/account/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    # post views
    path('', views.user_login, name='login'),
    path('register', views.register, name='register'),
]

testapp/testapp/apps/poebota/urls.py
# Создаём привязки для views
from django.urls import path
from . import views
app_name = 'poebota'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.create, name='create'),
]
#path('searc', views.searc, name='searc'),

testapp/testapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('poebota/', include('poebota.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

testapp/testapp/apps/account/models.py
from django.db import models

# Create your models here.

testapp/testapp/apps/poebota/models.py
from django.db import models
from django.utils import timezone

# Создаём модель своего приложения для базы данных
# Create your models here.


class Book(models.Model):
    book_autor = models.CharField('Автор', max_length=50)
    book_janr = models.CharField('Жанр', max_length=50)
    book_izdat = models.CharField('Издатель', max_length=50)
    book_name = models.CharField('Название', max_length=50)
    def __str__(self):
        return self.book_autor

class Bron(models.Model):
    object = models.ForeignKey(Book, on_delete=models.CASCADE)
    bron_status = models.CharField('Забронирована', max_length=50, default='Нет')
    bron_time = models.DateTimeField(default=timezone.now())
    bron_password = models.CharField('Пароль для бронирования', max_length=50, default='')
    bron_login = models.CharField('Логин', max_length=50, default='')
    def __str__(self):
        return self.bron_status

testapp/testapp/apps/account/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

testapp/testapp/apps/poebota/forms.py
from django import forms
from .models import Book, Bron
from django.contrib.auth.models import User


class SearcForm(forms.Form):
    autor = forms.CharField()
    janr = forms.CharField()
    izdat = forms.CharField()

class SearcForm1(forms.Form):
    def searced(autor, janr, izdat):
        books = Book.objects.filter(book_autor=autor, book_janr=janr, book_izdat=izdat)
        print(books)
        return books



testapp/testapp/apps/account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        print("1")
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/poebota/')
                #return render(request, 'account/login.html', {'form': form})
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

testapp/testapp/apps/poebota/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login
from .models import Book, Bron
from .forms import SearcForm, SearcForm1
from django.utils import timezone
from datetime import timedelta
# Создаём логику приложения
def index(request):

    if request.method == "POST":
        autor = request.POST.get("autor")
        janr = request.POST.get("janr")
        izdat = request.POST.get("izdat")
        books = Book.objects.filter(book_autor=autor, book_janr=janr, book_izdat=izdat)
        bron = Bron.objects.all()
        return render(request, "home/search.html", {'books': books, 'bron': bron})
    else:
        books = Book.objects.all()
        bron = Bron.objects.all()
        userform = SearcForm()
        return render(request, "index.html", {"form": userform, 'books': books, 'bron': bron})

def create(request, book_id):
    if request.method == "POST":
        bron_create = Bron.objects.get(id=book_id)
        if bron_create.bron_status == "Да" and bron_create.bron_login == request.POST.get("login") and bron_create.bron_password == request.POST.get("password"):
            bron_create.bron_status = "Нет"
            bron_create.bron_time = timezone.now()
            bron_create.bron_login = ""
            bron_create.bron_password = ""
            bron_create.save()
            print("бронь снята")
        elif bron_create.bron_status == "Нет":
            if request.user.is_authenticated == True:
                bron_create.bron_status = "Да"
                bron_create.bron_time = timezone.now() + timedelta(days=7)
                bron_create.bron_login = str(request.user)
                bron_create.bron_password = request.POST.get("password")
                bron_create.save()
                print("бронь установлена")
        else:
            raise Http404("Не верный логин или пароль")
    try:
        book = Book.objects.get(id=book_id)
        bron = Bron.objects.get(id=book_id)
    except:
        raise Http404("Книга не найдена")
    return render(request, 'home/create.html', {'book': book, 'bron': bron})


def get_data(request):
    return render(request, "home/home.html")


testapp/testapp/apps/account/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static  'css/stylesheet.css' %}" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div id="header">
    <span>Library</span>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

testapp/testapp/apps/poebota/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static  'css/stylesheet.css' %}" />
    <title>Not main str</title>
</head>
<body>
<p>Itog</p>
    {% block i %}

    {% endblock %}
</body>
</html>

testapp/testapp/apps/poebota/templates/home/create.html
{% extends 'home.html'%}
{% block i %}
<p>i</p>
<title>Library</title>
<p>Книга конкретная</p>
<div>
    <ln>Название:</ln><ln>{{book.book_name}}</ln></a></br>
    <ln>Автор:</ln><ln>{{book.book_autor}}</ln></br>
    <ln>Жанр:</ln><ln>{{book.book_janr}}</ln></br>
    <ln>Издатель:</ln><ln>{{book.book_izdat}}</ln></br>
    {%if bron.bron_status == "Да"%}
    <ln type="text" name="bron_id"  id="bron_id" >№:</ln><ln>{{book.id}}</ln></br>
        <ln name="bron_status">Статус бронирования:</ln><ln>{{bron.bron_status}}</ln></br>
        <ln name="bron_time">Время бронирования:</ln><ln>{{bron.bron_time}}</ln></br>
        <ln> Снять бронирование</ln></br>
        <form method="POST">
            {% csrf_token %}
        <label for="id_loginreset">Логин:</label>
        <input type="text" name="login" required="" id="id_loginreset"></br>
        <label for="id_passwordreset">Пароль:</label>
        <input type="text" name="password" required="" id="id_passwordreset"></br>
        <input type="submit" value="Send" ></br>
        </form>
    {%else%}
    <form method="POST">
            {% csrf_token %}
        <ln type="text" name="bron_id"  id="bron_id" >№:</ln><ln>{{book.id}}</ln></br>
        <ln name="bron_status">Статус бронирования:</ln><ln>{{bron.bron_status}}</ln></br>
        <ln name="bron_time">Время бронирования:</ln><ln>{{bron.bron_time}}</ln></br>
        <label for="id_password">Пароль: </label>
        <input type="text" name="password" required="" id="id_password"></br>
        <input type="submit" value="Send" ></br>
        {%endif%}
</form>
</div>

{% endblock %}

testapp/testapp/apps/poebota/templates/home/searc.html
{% extends 'home.html'%}


testapp/testapp/apps/poebota/templates/home/search.html
{% extends 'home.html'%}
{% block i %}
<p>Library</p>
<p>Найденые книги по запросу</p>

{% for o in books %}
<div>
    <a href = "{% url 'poebota:create' o.id %}"><ln>Название:</ln><ln>{{o.book_name}}</ln></a></br>
    <ln>Автор:</ln><ln>{{o.book_autor}}</ln></br>
    <ln>Жанр:</ln><ln>{{o.book_janr}}</ln></br>
    <ln>Издатель:</ln><ln>{{o.book_izdat}}</ln></br>
    <ln>№:</ln><ln>{{o.id}}</ln></br>
    {% for a in bron %}
    {%if o.id == a.id%}
        <ln>Статус бронирования:</ln><ln>{{a.bron_status}}</ln></br>
        <ln>Время бронирования:</ln><ln>{{a.bron_time}}</ln></br>
    {%endif%}
    {%endfor%}
</div>
{%endfor%}
{% endblock %}

testapp/testapp/apps/poebota/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static  'css/stylesheet.css' %}" />
    <title>Library</title>
</head>
<body>
<div>
    <p> Сервис для бронирования книг </p>
    {%if user.is_authenticated%}
    <p>Здравствуйте: {{user}}</p>
    {%else%}
    <p> Для начала работы <a href="{% url 'login' %}">выйдите</a> в аккаунт или <a href="{% url 'register' %}">зарегистрируйтесь</a> </p>
    {%endif%}
</div>
{%if user.is_authenticated%}
<div>
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
    </form>
    </div>
    <div>
        {%for b in books%}
            <div>
                <a href = "{% url 'poebota:create' b.id %}"><ln>Название:</ln><ln>{{b.book_name}}</ln></a></br>
                <ln>Автор:</ln><ln>{{b.book_autor}}</ln></br>
                <ln>Жанр:</ln><ln>{{b.book_janr}}</ln></br>
                <ln>Издатель:</ln><ln>{{b.book_izdat}}</ln></br>
                <ln>№:</ln><ln>{{b.id}}</ln></br>
                {% for q in bron %}
                {%if b.id == q.id%}
                    <ln>Статус бронирования:</ln><ln>{{q.bron_status}}</ln></br>
                    <ln>Время бронирования:</ln><ln>{{q.bron_time}}</ln></br>
                {%endif%}
                {%endfor%}
            </div>
        {%endfor%}
    </div>
{%endif%}
</body>
</html>